# Site settings
title:       "[IP]yandy"
email:       yr@ipyandy.net
author:      Yandy Ramirez
description: "Internetworking and Python for Engineers"
baseurl:     ""
url:         "http://ipyandy.net"

avatar: http://ipyandy.net/images/logo.png
logo: http://ipyandy.net/images/logo.png
image: http://ipyandy.net/images/logo.png
twitter_image: http://ipyandy.net/images/logo.png

# Google analytics
google_analytics: "UA-10501449-11"

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: ipyandy

# Social icons
github_username: IPyandy
stackoverflow_id:
twitter_username: IPyandy
google_plus_id: YandyRamirez
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
