# Site settings
title:       "[IP]yandy"
email:       yr@inetpy.com
author:      Yandy Ramirez
description: "Internetworking with Python for Engineers"
baseurl:     ""
url:         "http://inetpy.com"
# url: localhost:4000

avatar: http://inetpy.com/images/logo.png
logo: http://inetpy.com/images/logo.png
image: http://inetpy.com/images/logo.png
twitter_image: http://inetpy.com/images/logo.png

# Google analytics
google_analytics: "UA-10501449-11"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true
show_share_icons: true

excerpt_separator: "<!--more-->"

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: iyandy

# Social icons
github_username: IPyandy
stackoverflow_id:
twitter_username: IPyandy
google_plus_id: YandyRamirez
facebook: darksoul135
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
gems:
  - jekyll-sitemap
