# Harmony Jekyll theme general configurations 

# Base URL
baseurl: ""

# Site live URL
url: http://ipyandy.net

# Title
title: "[IP]yandy"

# Little description about your site
description: "Internetworking and Python for Engineers"

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: "[IP]yandy"
  # Little description about your site
  description: "Internetworking and Python for Engineers"
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: "Internetworking and Python for Engineers"
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Yandy Ramirez
    email: yandyr@gmail.com
    url: http://ipyandy.net

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: "UA-10501449-11"
  google_webmaster_key: "JK0nkBtXQdnSsTVouQvjuGrh0R_ub91t4__fI8QSEVk"

  # Profile links, leave blank to ignore
  social: 
    github: IPyandy
    twitter: IPyandy
    facebook: darksoul135
    gplus: +YandyRamirez
    dribble: 
    pinterest: 
    instagram: yandy_r
  # Toggle disclaimer in footer
  show_disclaimer: true

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: IPyandy

  # excerpt_separator: "<!--more-->"

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
